# report_generator.py
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import io
import os

def generate_security_report(analysis_data, ip_reputation_data=None):
    """Generate comprehensive PDF security report"""
    
    # Create PDF in memory
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        alignment=1  # Center
    )
    
    story.append(Paragraph("Security Analysis Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Executive Summary
    story.append(Paragraph("Executive Summary", styles['Heading2']))
    summary_text = f"""
    This report summarizes the security analysis conducted on {len(analysis_data.get('logs', []))} log entries.
    The analysis identified potential security threats and provides recommendations for mitigation.
    """
    story.append(Paragraph(summary_text, styles['Normal']))
    story.append(Spacer(1, 15))
    
    # Key Findings Table
    story.append(Paragraph("Key Findings", styles['Heading2']))
    
    findings_data = [
        ['Metric', 'Count'],
        ['Total Log Entries', len(analysis_data.get('logs', []))],
        ['High Severity Threats', analysis_data.get('stats', {}).get('high', 0)],
        ['Medium Severity Threats', analysis_data.get('stats', {}).get('medium', 0)],
        ['Low Severity Threats', analysis_data.get('stats', {}).get('low', 0)]
    ]
    
    findings_table = Table(findings_data, colWidths=[3*inch, 1.5*inch])
    findings_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(findings_table)
    story.append(Spacer(1, 20))
    
    # IP Reputation Section (if available)
    if ip_reputation_data:
        story.append(Paragraph("IP Reputation Analysis", styles['Heading2']))
        
        for ip, data in ip_reputation_data.items():
            if 'summary' in data:
                summary = data['summary']
                ip_text = f"IP: {ip} - Threat Level: {summary.get('threat_level', 'Unknown')}"
                story.append(Paragraph(ip_text, styles['Normal']))
        
        story.append(Spacer(1, 15))
    
    # Recommendations
    story.append(Paragraph("Security Recommendations", styles['Heading2']))
    recommendations = [
        "Monitor high-severity IP addresses for suspicious activity",
        "Implement network segmentation for critical assets",
        "Review and update firewall rules regularly",
        "Consider implementing intrusion detection systems",
        "Conduct regular security awareness training"
    ]
    
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", styles['Normal']))
    
    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph("Generated by Security Intelligence Platform", styles['Italic']))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    
    return buffer

def generate_ip_reputation_report(ip_data):
    """Generate detailed IP reputation PDF report"""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Title
    story.append(Paragraph("IP Reputation Analysis Report", styles['Heading1']))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 20))
    
    for ip, data in ip_data.items():
        story.append(Paragraph(f"IP Address: {ip}", styles['Heading2']))
        
        if 'summary' in data:
            summary = data['summary']
            
            # Summary Table
            summary_data = [
                ['Assessment', 'Value'],
                ['Overall Threat Level', summary.get('threat_level', 'Unknown')],
                ['Threat Score', f"{summary.get('overall_threat_score', 0)}/100"],
                ['Sources Checked', ', '.join(summary.get('sources_checked', []))]
            ]
            
            summary_table = Table(summary_data, colWidths=[2*inch, 4*inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(summary_table)
            story.append(Spacer(1, 15))
        
        # Detailed findings for each source
        story.append(Paragraph("Detailed Analysis", styles['Heading3']))
        
        for source, result in data.items():
            if source != 'summary' and 'error' not in result:
                source_text = f"{source}: "
                if 'threat_score' in result:
                    source_text += f"Threat Score: {result['threat_score']}%"
                elif 'abuseConfidenceScore' in result:
                    source_text += f"Abuse Score: {result['abuseConfidenceScore']}%"
                elif 'severity' in result:
                    source_text += f"Severity: {result['severity']}"
                
                story.append(Paragraph(source_text, styles['Normal']))
        
        story.append(Spacer(1, 20))
    
    doc.build(story)
    buffer.seek(0)
    return buffer